INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (1,'McLaren','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (2,'BMW Sauber','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (3,'Williams','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (4,'Renault','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (5,'Toro Rosso','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (6,'Ferrari','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (7,'Toyota','Japanese');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (8,'Super Aguri','Japanese');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (9,'Red Bull','Austrian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (10,'Force India','Indian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (11,'Honda','Japanese');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (12,'Spyker','Dutch');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (13,'MF1','Russian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (14,'Spyker MF1','Dutch');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (15,'Sauber','Swiss');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (16,'BAR','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (17,'Jordan','Irish');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (18,'Minardi','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (19,'Jaguar','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (20,'Prost','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (21,'Arrows','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (22,'Benetton','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (23,'Brawn','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (24,'Stewart','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (25,'Tyrrell','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (26,'Lola','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (27,'Ligier','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (28,'Forti','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (29,'Footwork','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (30,'Pacific','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (31,'Simtek','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (32,'Team Lotus','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (33,'Larrousse','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (34,'Brabham','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (35,'Dallara','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (36,'Fondmetal','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (37,'March','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (38,'Andrea Moda','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (39,'AGS','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (40,'Lambo','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (41,'Leyton House','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (42,'Coloni','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (44,'Euro Brun','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (45,'Osella','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (46,'Onyx','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (47,'Life','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (48,'Rial','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (49,'Zakspeed','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (50,'RAM','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (51,'Alfa Romeo','Swiss');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (52,'Spirit','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (53,'Toleman','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (54,'ATS','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (55,'Theodore','Hong Kong');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (56,'Fittipaldi','Brazilian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (57,'Ensign','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (58,'Shadow','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (59,'Wolf','Canadian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (60,'Merzario','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (61,'Kauhsen','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (62,'Rebaque','Mexican');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (63,'Surtees','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (64,'Hesketh','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (65,'Martini','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (66,'BRM','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (67,'Penske','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (68,'LEC','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (69,'McGuire','Australian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (70,'Boro','Dutch');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (71,'Apollon','Swiss');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (72,'Kojima','Japanese');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (73,'Parnelli','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (74,'Maki','Japanese');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (75,'Embassy Hill','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (76,'Lyncar','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (77,'Trojan','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (78,'Amon','New Zealander');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (79,'Token','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (80,'Iso Marlboro','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (81,'Tecno','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (82,'Matra','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (83,'Politoys','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (84,'Connew','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (85,'Bellasi','Swiss');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (86,'De Tomaso','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (87,'Cooper','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (88,'Eagle','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (89,'LDS','South African');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (90,'Protos','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (91,'Shannon','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (92,'Scirocco','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (93,'RE','Rhodesian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (94,'BRP','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (95,'Porsche','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (96,'Derrington','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (97,'Gilby','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (98,'Stebro','Canadian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (99,'Emeryson','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (100,'ENB','Belgian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (101,'JBW','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (102,'Ferguson','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (103,'MBM','Swiss');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (104,'Behra-Porsche','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (105,'Maserati','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (106,'Scarab','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (107,'Watson','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (108,'Epperly','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (109,'Phillips','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (110,'Lesovsky','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (111,'Trevis','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (112,'Meskowski','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (113,'Kurtis Kraft','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (114,'Kuzma','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (115,'Christensen','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (116,'Ewing','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (117,'Aston Martin','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (118,'Vanwall','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (119,'Moore','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (120,'Dunn','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (121,'Elder','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (122,'Sutton','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (123,'Fry','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (124,'Tec-Mec','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (125,'Connaught','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (126,'Alta','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (127,'OSCA','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (128,'Gordini','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (129,'Stevens','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (130,'Bugatti','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (131,'Mercedes','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (132,'Lancia','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (133,'HWM','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (134,'Schroeder','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (135,'Pawl','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (136,'Pankratz','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (137,'Arzani-Volpini','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (138,'Nichels','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (139,'Bromme','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (140,'Klenk','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (141,'Simca','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (142,'Turner','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (143,'Del Roy','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (144,'Veritas','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (145,'BMW','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (146,'EMW','East German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (147,'AFM','German');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (148,'Frazer Nash','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (149,'Sherman','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (150,'Deidt','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (151,'ERA','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (152,'Aston Butterworth','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (153,'Cisitalia','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (154,'Talbot-Lago','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (155,'Hall','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (156,'Marchese','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (157,'Langley','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (158,'Rae','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (159,'Olson','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (160,'Wetteroth','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (161,'Adams','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (162,'Snowberger','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (163,'Milano','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (164,'HRT','Spanish');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (167,'Cooper-Maserati','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (166,'Virgin','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (168,'Cooper-OSCA','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (169,'Cooper-Borgward','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (170,'Cooper-Climax','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (171,'Cooper-Castellotti','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (172,'Lotus-Climax','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (173,'Lotus-Maserati','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (174,'De Tomaso-Osca','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (175,'De Tomaso-Alfa Romeo','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (176,'Lotus-BRM','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (177,'Lotus-Borgward','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (178,'Cooper-Alfa Romeo','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (179,'De Tomaso-Ferrari','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (180,'Lotus-Ford','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (181,'Brabham-BRM','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (182,'Brabham-Ford','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (183,'Brabham-Climax','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (184,'LDS-Climax','South African');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (185,'LDS-Alfa Romeo','South African');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (186,'Cooper-Ford','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (187,'McLaren-Ford','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (188,'McLaren-Serenissima','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (189,'Eagle-Climax','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (190,'Eagle-Weslake','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (191,'Brabham-Repco','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (192,'Cooper-Ferrari','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (193,'Cooper-ATS','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (194,'McLaren-BRM','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (195,'Cooper-BRM','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (196,'Matra-Ford','French');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (197,'BRM-Ford','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (198,'McLaren-Alfa Romeo','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (199,'March-Alfa Romeo','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (200,'March-Ford','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (201,'Lotus-Pratt &amp; Whitney','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (202,'Shadow-Ford','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (203,'Shadow-Matra','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (204,'Brabham-Alfa Romeo','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (205,'Lotus','Malaysian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (206,'Marussia','Russian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (207,'Caterham','Malaysian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (208,'Lotus F1','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (209,'Manor Marussia','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (210,'Haas F1 Team','American');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (211,'Racing Point','British');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (213,'AlphaTauri','Italian');
INSERT INTO constructors(constructorID,constructorName,constructorNationality) VALUES (214,'Alpine F1 Team','French');
